# REWEIGHTING CONF FILE
# This file contains all reweighings...
#
# 
# Marcos Romero Lamas (mromerol@cern.ch)


# Kinematic reweighings to Bs {{{
#    These are the general reweightings to be done. They are used in the 
#    time acceptable pipeline. Everything is reweighted to Bs, and non=-Bs MC
#    are also reweighted to a previopusly reweighted Bx sample.

kbsWeight:
  MC_Bs2JpsiPhi: &kbsWeight_MC_Bs2JpsiPhi
    # BsMC -> BsRD
    original: ["{sWeight}*polWeight*pdfWeight"]
    target: ["{sWeight}"]
    variables: ["B_PT", "X_M"]
  
  MC_Bs2JpsiPhi_dG0: 
    # BsMC -> BsRD
    <<: *kbsWeight_MC_Bs2JpsiPhi 
  
  MC_Bs2JpsiKK_Swave: 
    # BsMC -> BsRD
    <<: *kbsWeight_MC_Bs2JpsiPhi 

  MC_Bd2JpsiKstar: 
    # BdMC -> BdRD
    original: ["{sWeight}*polWeight*pdfWeight"]
    target: ["{sWeight}*kbsWeight"]
    variables: ["B_PT", "X_M"]

  MC_Bu2JpsiKplus:
    # BuMC -> BuRD
    original: ["{sWeight}*polWeight"]
    target: ["{sWeight}*kbsWeight"]
    variables: ["B_PT"]
  
  Bd2JpsiKstar:
    # BdRD -> BsRD
    original: ["{sWeight}"]
    target: ["{sWeight}"]
    variables: ["B_PT", "B_P"]
  
  Bu2JpsiKplus:
    # BuRD -> BsRD
    original: ["{sWeight}"]
    target: ["{sWeight}"]
    variables: ["B_PT", "B_P"]

  Bs2DsPi:
    # BsRD -> BsRD
    original: ["{sWeight}"]
    target: ["{sWeight}"]
    variables: ["B_PT", "nPVs", "nTracks", "B_ETA"]

# }}}


# Kinematic reweighings to Bu {{{
#    For some cross validation we use Bu as proxy for Bs, hence we need
#    a set of weights computed the same way we do in Bs.

kbuWeight:
  MC_Bs2JpsiPhi: &kbuWeight_MC_Bs2JpsiPhi
    original: ["{sWeight}*polWeight*pdfWeight"]
    target: ["{sWeight}*kbuWeight"]
    variables: ["B_PT", "X_M"]
  
  MC_Bs2JpsiPhi_dG0: 
    <<: *kbuWeight_MC_Bs2JpsiPhi 
  
  MC_Bs2JpsiKK_Swave: 
    <<: *kbuWeight_MC_Bs2JpsiPhi 
  
  MC_Bd2JpsiKstar: 
    original: ["{sWeight}*polWeight*pdfWeight"]
    target: ["{sWeight}*kbuWeight"]
    variables: ["B_PT", "X_M"]

  MC_Bu2JpsiKplus:
    original: ["{sWeight}*polWeight"]
    target: ["{sWeight}"]
    variables: ["B_PT"]
  
  Bd2JpsiKstar:
    original: ["{sWeight}"]
    target: ["{sWeight}"]
    variables: ["B_PT", "B_P"]
  
  Bs2JpsiPhi:
    original: ["{sWeight}"]
    target: ["{sWeight}"]
    variables: ["B_PT", "B_P"]

# }}}


# Kinematic reweighings to Bd {{{
#    For some cross validation Bd samples and we try to measure Bd lifetimes
#    using Bd MC for the decay time efficiency. Hence, we need a set of 
#    reweighs for Bd MC to Bd RD only.

kbdWeight:
  MC_Bs2JpsiPhi: &kbdWeight_MC_Bs2JpsiPhi
    original: ["{sWeight}*polWeight*pdfWeight"]
    target: ["{sWeight}*kbdWeight"]
    variables: ["B_PT", "X_M"]
  
  MC_Bs2JpsiPhi_dG0:
    <<: *kbdWeight_MC_Bs2JpsiPhi 

  MC_Bs2JpsiKK_Swave:
    <<: *kbdWeight_MC_Bs2JpsiPhi 
  
  MC_Bd2JpsiKstar: 
    original: ["{sWeight}*polWeight*pdfWeight"]
    target: ["{sWeight}"]
    variables: ["B_PT", "X_M"]

  MC_Bu2JpsiKplus:
    original: ["{sWeight}*polWeight"]
    target: ["{sWeight}*kbdWeight"]
    variables: ["B_PT"]
  
  Bs2JpsiPhi:
    original: ["{sWeight}"]
    target: ["{sWeight}"]
    variables: ["B_PT", "B_P"]
  
  Bu2JpsiKplus:
    original: ["{sWeight}"]
    target: ["{sWeight}"]
    variables: ["B_PT", "B_P"]

# }}}


# Kinematic Odd reweightings {{{
#    The oddWeight is a weight used for MC cross-validation of the baeline procedure.
#    oddWeights try to introduce MC-RD differences in half o the MC sample.

oddWeight:
  # These are the general reweightings to be done. They are used in the 
  # time acceptable pipeline. Everything is reweighted to Bs, and non=-Bs MC
  # are also reweighted to a previopusly reweighted Bx sample.
  MC_Bs2JpsiPhi: &oddWeight_MC_Bs2JpsiPhi
    original: ["{sWeight}*polWeight*pdfWeight"]
    target: ["{sWeight}"]
    variables: ["log_B_IPCHI2_mva", "B_DTF_CHI2NDOF", "hplus_TRACK_CHI2NDOF",
                "hplus_PIDK", "hminus_TRACK_CHI2NDOF", "muplus_TRACK_CHI2NDOF",
                "muminus_TRACK_CHI2NDOF", "max_K_TRCHI2_mva", "max_mu_TRCHI2_mva"]
  
  MC_Bs2JpsiPhi_dG0:
    <<: *oddWeight_MC_Bs2JpsiPhi 

  MC_Bs2JpsiKK_Swave:
    <<: *oddWeight_MC_Bs2JpsiPhi 
  
  MC_Bd2JpsiKstar:
    <<: *oddWeight_MC_Bs2JpsiPhi 
    original: ["{sWeight}*polWeight*pdfWeight"]
    target: ["{sWeight}*kbsWeight"]

  MC_Bu2JpsiKplus:
    <<: *oddWeight_MC_Bs2JpsiPhi 
    original: ["{sWeight}*polWeight"]
    target: ["{sWeight}*kbsWeight"]
  
  Bd2JpsiKstar:
    <<: *oddWeight_MC_Bs2JpsiPhi 
    original: ["{sWeight}"]
    target: ["{sWeight}"]
  
  Bu2JpsiKplus:
    <<: *oddWeight_MC_Bs2JpsiPhi 
    original: ["{sWeight}"]
    target: ["{sWeight}"]

# }}}


# phiHH reweightings {{{
#    The oddWeight is a weight used for MC cross-validation of the baeline procedure.
#    oddWeights try to introduce MC-RD differences in half o the MC sample.

phiWeight:
  # These are the general reweightings to be done. They are used in the 
  # time acceptable pipeline. Everything is reweighted to Bs, and non=-Bs MC
  # are also reweighted to a previopusly reweighted Bx sample.
  MC_Bs2JpsiPhi: &phiWeight_MC_Bs2JpsiPhi
    original: ["{sWeight}"]
    target: ["{sWeight}"]
    variables: ["phiHH"]
  
  MC_Bs2JpsiPhi_dG0:
    <<: *phiWeight_MC_Bs2JpsiPhi 

  MC_Bs2JpsiKK_Swave:
    <<: *phiWeight_MC_Bs2JpsiPhi 
  
  MC_Bd2JpsiKstar:
    <<: *phiWeight_MC_Bs2JpsiPhi 
    original: ["{sWeight}"]
    target: ["{sWeight}"]

  MC_Bu2JpsiKplus:
    <<: *phiWeight_MC_Bs2JpsiPhi 
    original: ["{sWeight}"]
    target: ["{sWeight}"]
  
  Bd2JpsiKstar:
    <<: *phiWeight_MC_Bs2JpsiPhi 
    original: ["{sWeight}"]
    target: ["{sWeight}"]
  
  Bu2JpsiKplus:
    <<: *phiWeight_MC_Bs2JpsiPhi 
    original: ["{sWeight}"]
    target: ["{sWeight}"]

# }}}


# vim:foldmethod=marker
