# [tool.isort]
# line_length = 88
# indent = 2

[tool.autopep8]
max_line_length = 79
ignore = "E501,W6"  # or ["E501", "W6"]
# in_place = true
# recursive = true
# aggressive = 3
indent_size = 2
trim_trailing_whitespace = true

[flake8]
max_line_length = 79
indent_size = 2
extend-ignore = "E203,E111"

[tool.flake8]
max-line-length = 79
indent-size = 2
extend-ignore = "E203,E111"
