# BDT CONFIG FILE
#
#
# Author: Marcos Romero Lamas (mromerol@cern.ch)


# Mode selection
# Choose with in which mode is trained the BDT to select the mode with
# Only two modes have rules for training: Bs and Bu
bdt_mode:
  Bs2JpsiPhi: Bs2JpsiPhi
  Bs2JpsiPhi_Lb: Bs2JpsiPhi
  Bd2JpsiKstar: Bs2JpsiPhi
  Bs2JpsiPhi_Prompt: Bs2JpsiPhi
  Bu2JpsiKplus: Bu2JpsiKplus
  MC_Bs2JpsiPhi: Bs2JpsiPhi
  MC_Bs2JpsiKK_Swave: Bs2JpsiPhi #Check if it's not better to use MC_Bs2JpsiKK_Swave
  MC_Bs2JpsiPhi_dG0: Bs2JpsiPhi
  MC_Bs2JpsiPhi_dG0_large_lifetime: Bs2JpsiPhi
  MC_Bs2JpsiPhi_Prompt: Bs2JpsiPhi
  MC_Bd2JpsiKstar: Bs2JpsiPhi
  MC_Bu2JpsiKplus: Bu2JpsiKplus
  MC_Bs2JpsiPhi_fromLb: Bs2JpsiPhi
  MC_Bc2BsPi: Bs2JpsiPhi


bdt_cutoff:
  Bs2JpsiPhi: -1.0
  Bu2JpsiKplus: -1.0


bdt_branch:
  Bs2JpsiPhi: "bdtg3"
  Bu2JpsiKplus: "bdtg3"


# Year selection
# Choose with in which year is trained the BDT to select the year with
# 2015 is usually trained with 2016 because stats in 2015 as very low
bdt_year:
  '2015': '2016'
  '2016': '2016'
  '2017': '2017'
  '2018': '2018'


mass_model:
  'Bs2JpsiPhi': 'dgauss'
  'Bd2JpsiKstar': 'dgauss'
  'Bu2JpsiKplus': 'dgauss'


mass_branch:
  'Bs2JpsiPhi': 'B_ConstJpsi_M_1'
  'MC_Bs2JpsiPhi': 'B_ConstJpsi_M_1'
  'MC_Bs2JpsiPhi_dG0': 'B_ConstJpsi_M_1'
  'Bd2JpsiKstar': 'B_ConstJpsi_M_1'
  'MC_Bd2JpsiKstar': 'B_ConstJpsi_M_1'
  'Bu2JpsiKplus': 'B_ConstJpsi_M_1'
  'MC_Bu2JpsiKplus': 'B_ConstJpsi_M_1'


# vim: fdm=marker
