multiple_candidates: "Multiple candidates"
mass_factorization: "Mass factorization"
mass_shape: "Mass shape"
csp_factors: "$C_{SP}$ factors"
timeres_prompt: "Time res. prompt"
timeres_statistical: "Time res. statistical"
timeres_mu: "Time res. $mu$"
timeres_wpv: "Time res. WPV"
quadratic_tagging: "Quadratic tagging"
angacc_statistical: "Angular acceptance statistical"
angacc_correction: "Angular acceptance correction"
angacc_timesigmat: "Angular acceptance t, sigmat dependence"
