jobscript: "grid-jobscript.sh"
cluster: "grid-submit.py"
cluster-status: "grid-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: 100
restart-times: 3
local-cores: 64
jobs: 10
verbose: false
